server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.access: INFO

management.endpoints.web.exposure.include: metrics
management.tracing.sampling.probability: 1.0